import {
  fanblade1,
  fanblade2,
  fanblade3,
  fanblade4,
  fanblade5,
  fanblade6,
  fanblade7,
  fanblade8,
  fanblade9,
  fanblade10,
  fanblade11,
  fanblade12,
  fanblade13,
  fanblade14,
  fanblade15,
  fanblade16,
} from "../../assets";
export const FANBLADES = [
  {
    image: fanblade1,
    title: "fanblade1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade2,
    title: "fanblade2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade3,
    title: "fanblade3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade4,
    title: "fanblade4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade5,
    title: "fanblade5",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade6,
    title: "fanblade6",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade7,
    title: "fanblade7",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade8,
    title: "fanblade8",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade9,
    title: "fanblade9",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade10,
    title: "fanblade10",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade11,
    title: "fanblade11",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade12,
    title: "fanblade12",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade13,
    title: "fanblade13",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade14,
    title: "fanblade14",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade15,
    title: "fanblade15",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade16,
    title: "fanblade16",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
