import {
  ring1,
  ring2,
  ring3,
  ring4,
  ring5,
  ring6,
  ring7,
  ring8,
  ring9,
  ring10,
} from "../../assets";
export const MOTOR_RINGS = [
  {
    image: ring1,
    title: "ring1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring2,
    title: "ring2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring3,
    title: "ring3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring4,
    title: "ring4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring5,
    title: "ring5",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring6,
    title: "ring6",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring7,
    title: "ring7",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring8,
    title: "ring8",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring9,
    title: "ring9",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring10,
    title: "ring10",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
