import {
  coolerStand1,
  coolerStand2,
  coolerStand3,
  coolerStand4,
  wms1,
  wms2,
  wms3,
  wms4,
  wms5,
  wms6,
  wms7,
  wms8,
  wms9,
  wms10,
  wms11,
  wms12,
  acs_wallmounted1,
  acs_wallmounted2,
  acs_wallmounted3,
  acs_wallmounted4,
  acs_wallmounted5,
  acs_wallmounted6,
} from "../../assets";

export const STANDS = [
  {
    image: coolerStand1,
    images: [coolerStand1, coolerStand2, coolerStand3, coolerStand4],
    title: "Cooler Stand",
    description: "Available in adjustable as well as fixed sizes",
  },
  {
    image: wms1,
    images: [
      wms1,
      wms2,
      wms5,
      wms6,
      wms7,
      wms8,
      wms10,
      wms11,
      wms12,
      wms3,
      wms4,
    ],
    title: "Washing Machine Stand",
  },
  {
    image: acs_wallmounted1,
    images: [
      acs_wallmounted1,
      acs_wallmounted2,
      acs_wallmounted3,
      acs_wallmounted4,
      acs_wallmounted5,
      acs_wallmounted6,
    ],
    title: "Air Conditioner Stand (Wall Mounted)",
  },
];
