import {
  cover1,
  fanblade1,
  motorComponent1,
  ring1,
  pedestralFan1,
  cover2,
  fanblade2,
  motorComponent2,
  ring2,
  pedestralFan2,
  cover3,
  fanblade3,
  ring3,
  pedestralFan3,
  cover4,
  fanblade4,
  ring4,
  pedestralFan4,
  cover5,
  fanblade5,
  ring5,
  cover6,
  fanblade6,
  ring6,
  motorComponent3,
  motorComponent4,
  motorComponent5,
  motorComponent6,
  cover7,
  cover8,
  cover9,
  cover10,
  cover11,
  cover12,
  cover13,
  fanblade7,
  fanblade8,
  fanblade9,
  fanblade10,
  fanblade11,
  fanblade12,
  fanblade13,
  fanblade14,
  fanblade15,
  fanblade16,
  ring7,
  ring8,
  ring9,
  ring10,
  cooler3,
  cooler2,
  cooler1,
  coolerStand1,
  coolerMotor2,
  coolerMotor1,
} from "../assets";

export const products = [
  {
    title: "Cover1",
    link: "https://indotechengineering.in/",
    thumbnail: cover1,
  },
  {
    title: "fanblade1",
    link: "https://indotechengineering.in/",
    thumbnail: fanblade1,
  },

  {
    title: "motorComponent1",
    link: "https://indotechengineering.in/",
    thumbnail: motorComponent1,
  },

  {
    title: "ring1",
    link: "https://indotechengineering.in/",
    thumbnail: ring1,
  },
  {
    title: "pedestralFan1",
    link: "https://indotechengineering.in/",
    thumbnail: pedestralFan1,
  },
  {
    title: "cover2",
    link: "https://indotechengineering.in/",
    thumbnail: cover2,
  },

  {
    title: "fanblade2",
    link: "https://indotechengineering.in/",
    thumbnail: fanblade2,
  },
  {
    title: "motorComponent2",
    link: "https://indotechengineering.in/",
    thumbnail: motorComponent2,
  },
  {
    title: "ring2",
    link: "https://indotechengineering.in/",
    thumbnail: ring2,
  },
  {
    title: "pedestralFan2",
    link: "https://indotechengineering.in/",
    thumbnail: pedestralFan2,
  },
  {
    title: "cover3",
    link: "https://indotechengineering.in/",
    thumbnail: cover3,
  },

  {
    title: "fanblade3",
    link: "https://indotechengineering.in/",
    thumbnail: fanblade3,
  },
  {
    title: "motorComponent3",
    link: "https://indotechengineering.in/",
    thumbnail: motorComponent3,
  },
  {
    title: "ring3",
    link: "https://indotechengineering.in/",
    thumbnail: ring3,
  },
  {
    title: "pedestralFan3",
    link: "https://indotechengineering.in/",
    thumbnail: pedestralFan3,
  },
  {
    title: "cover4",
    link: "https://indotechengineering.in/",
    thumbnail: cover4,
  },
  {
    title: "fanblade4",
    link: "https://indotechengineering.in/",
    thumbnail: fanblade4,
  },
  {
    title: "motorComponent4",
    link: "https://indotechengineering.in/",
    thumbnail: motorComponent4,
  },
  {
    title: "ring4",
    link: "https://indotechengineering.in/",
    thumbnail: ring4,
  },
  {
    title: "pedestralFan4",
    link: "https://indotechengineering.in/",
    thumbnail: pedestralFan4,
  },
  {
    title: "cover5",
    link: "https://indotechengineering.in/",
    thumbnail: cover5,
  },
  {
    title: "fanblade5",
    link: "https://indotechengineering.in/",
    thumbnail: fanblade5,
  },
  {
    title: "motorComponent5",
    link: "https://indotechengineering.in/",
    thumbnail: motorComponent5,
  },
  {
    title: "ring5",
    link: "https://indotechengineering.in/",
    thumbnail: ring5,
  },
  {
    title: "cover6",
    link: "https://indotechengineering.in/",
    thumbnail: cover6,
  },
  {
    title: "fanblade6",
    link: "https://indotechengineering.in/",
    thumbnail: fanblade6,
  },
  {
    title: "motorComponent6",
    link: "https://indotechengineering.in/",
    thumbnail: motorComponent6,
  },
  {
    title: "ring6",
    link: "https://indotechengineering.in/",
    thumbnail: ring6,
  },
];
export const coolers = [
  {
    image: cooler1,
    title: "cooler1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cooler2,
    title: "cooler2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cooler3,
    title: "cooler3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
export const coolersAccessories = [
  {
    image: coolerStand1,
    title: "coolerStand1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: coolerMotor1,
    title: "coolerMotor1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: coolerMotor2,
    title: "coolerMotor2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];

export const covers = [
  {
    image: cover1,
    title: "Cover1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover2,
    title: "Cover2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover3,
    title: "Cover3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover4,
    title: "Cover4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover5,
    title: "Cover5",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover6,
    title: "Cover6",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover7,
    title: "Cover7",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover8,
    title: "Cover8",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover9,
    title: "Cover9",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover10,
    title: "Cover10",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover11,
    title: "Cover11",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover12,
    title: "Cover12",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: cover13,
    title: "Cover13",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
export const fanblades = [
  {
    image: fanblade1,
    title: "fanblade1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade2,
    title: "fanblade2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade3,
    title: "fanblade3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade4,
    title: "fanblade4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade5,
    title: "fanblade5",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade6,
    title: "fanblade6",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade7,
    title: "fanblade7",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade8,
    title: "fanblade8",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade9,
    title: "fanblade9",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade10,
    title: "fanblade10",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade11,
    title: "fanblade11",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade12,
    title: "fanblade12",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade13,
    title: "fanblade13",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade14,
    title: "fanblade14",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade15,
    title: "fanblade15",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: fanblade16,
    title: "fanblade16",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
export const motorComponents = [
  {
    image: motorComponent1,
    title: "motorComponent1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: motorComponent2,
    title: "motorComponent2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: motorComponent3,
    title: "motorComponent3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: motorComponent4,
    title: "motorComponent4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: motorComponent5,
    title: "motorComponent5",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: motorComponent6,
    title: "motorComponent6",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
export const motorRings = [
  {
    image: ring1,
    title: "ring1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring2,
    title: "ring2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring3,
    title: "ring3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring4,
    title: "ring4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring5,
    title: "ring5",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring6,
    title: "ring6",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring7,
    title: "ring7",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring8,
    title: "ring8",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring9,
    title: "ring9",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: ring10,
    title: "ring10",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
export const pedestralFan = [
  {
    image: pedestralFan1,
    title: "pedestralFan1",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: pedestralFan2,
    title: "pedestralFan2",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: pedestralFan3,
    title: "pedestralFan3",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
  {
    image: pedestralFan4,
    title: "pedestralFan4",
    description: "Short description",
    price: "$450",
    sizes: ['15"', '16"', '17"', '18"'],
  },
];
